# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1891, 1061))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.infoWeather3 = QtWidgets.QLabel(self.layoutWidget)
        self.infoWeather3.setObjectName("infoWeather3")
        self.gridLayout.addWidget(self.infoWeather3, 2, 5, 1, 1)
        self.infoWeather2 = QtWidgets.QLabel(self.layoutWidget)
        self.infoWeather2.setObjectName("infoWeather2")
        self.gridLayout.addWidget(self.infoWeather2, 2, 3, 1, 1)
        self.imageWeather2 = QtWidgets.QLabel(self.layoutWidget)
        self.imageWeather2.setMinimumSize(QtCore.QSize(500, 500))
        self.imageWeather2.setObjectName("imageWeather2")
        self.gridLayout.addWidget(self.imageWeather2, 0, 3, 1, 1)
        self.imageWeather1 = QtWidgets.QLabel(self.layoutWidget)
        self.imageWeather1.setMinimumSize(QtCore.QSize(500, 500))
        self.imageWeather1.setObjectName("imageWeather1")
        self.gridLayout.addWidget(self.imageWeather1, 0, 1, 1, 1)
        self.day2 = QtWidgets.QLabel(self.layoutWidget)
        self.day2.setObjectName("day2")
        self.gridLayout.addWidget(self.day2, 1, 3, 1, 1)
        self.imageWeather3 = QtWidgets.QLabel(self.layoutWidget)
        self.imageWeather3.setMinimumSize(QtCore.QSize(500, 500))
        self.imageWeather3.setObjectName("imageWeather3")
        self.gridLayout.addWidget(self.imageWeather3, 0, 5, 1, 1)
        self.infoWeather1 = QtWidgets.QLabel(self.layoutWidget)
        self.infoWeather1.setObjectName("infoWeather1")
        self.gridLayout.addWidget(self.infoWeather1, 2, 1, 1, 1)
        self.day1 = QtWidgets.QLabel(self.layoutWidget)
        self.day1.setObjectName("day1")
        self.gridLayout.addWidget(self.day1, 1, 1, 1, 1)
        self.day3 = QtWidgets.QLabel(self.layoutWidget)
        self.day3.setObjectName("day3")
        self.gridLayout.addWidget(self.day3, 1, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.infoWeather3.setText(_translate("Form", "TextLabel"))
        self.infoWeather2.setText(_translate("Form", "TextLabel"))
        self.imageWeather2.setText(_translate("Form", "TextLabel"))
        self.imageWeather1.setText(_translate("Form", "TextLabel"))
        self.day2.setText(_translate("Form", "TextLabel"))
        self.imageWeather3.setText(_translate("Form", "TextLabel"))
        self.infoWeather1.setText(_translate("Form", "TextLabel"))
        self.day1.setText(_translate("Form", "TextLabel"))
        self.day3.setText(_translate("Form", "TextLabel"))
